### ISSUE TITLE
Incompatibility with Godlike Faces

### ISSUE THREAD

**Issue by NexusSfan** [abb2k/demonify#1]
It shows the normal demon face instead of the mythic version
![image](https://github.com/user-attachments/assets/4480bf6b-c6d6-4d32-b2d3-74c81caa2292)

**Comment by abb2k** [comment]
well idk if that is a problem demonify is meant to make every demon demon so

**Comment by NexusSfan** [comment]
Well the godlike faces mod does have a Mythic Version of the hard demon face
